### ISSUE TITLE
Distribution de theta vs distribution s|theta

### ISSUE THREAD

**Issue by NicholasLangevin** [gabrielcrepeault/latex-template#2]
![image](https://user-images.githubusercontent.com/34043424/53305468-fd044c80-384f-11e9-9136-838ff98875a2.png)

Est-ce que mu(theta) ne serais pas plus la distribution de s|theta ?? 

![image](https://user-images.githubusercontent.com/34043424/53305474-0f7e8600-3850-11e9-827a-538a65e30237.png)

**Comment by gabrielcrepeault** [comment]
Est-ce que tu parle de u(theta) la dernière ligne dans le description? où j'ai marqué fct de densité/mass de probabilité?

u(theta) est la distribution a priori, mais \mu(\theta) est bel et bien la prime de risque, c'est juste que le u et le mu se ressemble beaucoup.

![capture d ecran le 2019-02-24 a 16 28 40](https://user-images.githubusercontent.com/31630059/53305589-4608d080-3851-11e9-9bf8-823f41a63ceb.png)

**Comment by NicholasLangevin** [comment]
Wow, c'est la une subtilité que je n'avais pas remarquer! Thx
